const mongoose = require("mongoose");

const resultSchema = new mongoose.Schema(
  {
    ownerProject: {
      type: mongoose.Types.ObjectId,
      ref: "User",
    },
    projectName: {
      type: String,
      trim: true,
    },
    typeMode: {
      type: String,
      enum: ["Basic", "Intermediate", "Detailed"],
    },
    sizeType: {
      type: String,
    },
    language: {
      type: String,
    },
    functionPoints: {
      type: Number,
      min: 0,
    },
    newSize: {
      type: Number,
      min: 0,
    },
    reusedSize: {
      type: Number,
      min: 0,
    },
    reusedIM: {
      type: Number,
      min: 0,
      max: 100,
    },
    reusedAA: {
      type: Number,
      min: 0,
      max: 8,
    },
    PREC: {
      type: String,
      required: true,
      default: "nominal",
    },
    FLEX: {
      type: String,
      required: true,
      default: "nominal",
    },
    RESL: {
      type: String,
      required: true,
      default: "nominal",
    },
    TEAM: {
      type: String,
      required: true,
      default: "nominal",
    },
    PMAT: {
      type: String,
      required: true,
      default: "nominal",
    },
    RELY: {
      type: String,
      required: true,
      default: "nominal",
    },
    DATA: {
      type: String,
      required: true,
      default: "nominal",
    },
    CPLX: {
      type: String,
      required: true,
      default: "nominal",
    },
    RUSE: {
      type: String,
      required: true,
      default: "nominal",
    },
    DOCU: {
      type: String,
      required: true,
      default: "nominal",
    },
    ACAP: {
      type: String,
      required: true,
      default: "nominal",
    },
    PCAP: {
      type: String,
      required: true,
      default: "nominal",
    },
    PCON: {
      type: String,
      required: true,
      default: "nominal",
    },
    AEXP: {
      type: String,
      required: true,
      default: "nominal",
    },
    PEXP: {
      type: String,
      required: true,
      default: "nominal",
    },
    LTEX: {
      type: String,
      required: true,
      default: "nominal",
    },
    TIME: {
      type: String,
      required: true,
      default: "nominal",
    },
    STOR: {
      type: String,
      required: true,
      default: "nominal",
    },
    PVOL: {
      type: String,
      required: true,
      default: "nominal",
    },
    TOOL: {
      type: String,
      required: true,
      default: "nominal",
    },
    SITE: {
      type: String,
      required: true,
      default: "nominal",
    },
    SCED: {
      type: String,
      required: true,
      default: "nominal",
    },
    softwareMaintenance: {
      type: String,
      required: true,
      default: "Off",
    },
    softwareLaborCostPerPM: {
      type: Number,
      min: 0,
    },
    // Software Development (Elaboration and Construction)
    softwareEAF: {
      type: Number,
      min: 0,
    },
    sizeExponent: {
      type: Number,
      min: 0,
    },
    scheduleExponent: {
      type: Number,
      min: 0,
    },
    softwareEffort: {
      type: Number,
      min: 0,
    },
    softwareSchedule: {
      type: Number,
      min: 0,
    },
    totalEquivalentSize: {
      type: Number,
      min: 0,
    },
    cost: {
      type: Number,
      min: 0,
    },
    // Acquisition Phase Distribution table
    inceptionAverageStaff: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    elaborationAverageStaff: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    constructionAverageStaff: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    transitionAverageStaff: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    inceptionEffort: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    elaborationEffort: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    constructionEffort: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    transitionEffort: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    inceptionSchedule: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    elaborationSchedule: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    constructionSchedule: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    transitionSchedule: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    inceptionCost: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    elaborationCost: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    constructionCost: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    transitionCost: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    // Software Effort Distribution for RUP/MBASE (Person-Months)
    managementInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    environmentPerCMInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    requirementsInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    designInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    implementationInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    assessmentInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    deploymentInception: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    managementElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    environmentPerCMElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    requirementsElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    designElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    implementationElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    assessmentElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    deploymentElaboration: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    managementConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    environmentPerCMConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    requirementsConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    designConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    implementationConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    assessmentConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    deploymentConstruction: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    managementTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    environmentPerCMTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    requirementsTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    designTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    implementationTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    assessmentTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
    deploymentTransition: {
      type: Number,
      trim: true,
      required: true,
      default: 0,
      min: 0,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Result", resultSchema);
